/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formuarios;


/**
 *
 * @author oscar
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    
      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuPersonas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuTaxis = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuCooperativas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuEntradaSalida = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Control de Taxi");

        jMenu1.setText("Mantenimiento");
        jMenu1.add(jSeparator1);

        mnuPersonas.setText("Personas");
        mnuPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPersonasActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPersonas);
        jMenu1.add(jSeparator2);

        mnuTaxis.setText("Taxis");
        mnuTaxis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTaxisActionPerformed(evt);
            }
        });
        jMenu1.add(mnuTaxis);
        jMenu1.add(jSeparator3);

        mnuCooperativas.setText("Cooperativa");
        mnuCooperativas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCooperativasActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCooperativas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimientos");

        mnuEntradaSalida.setText("Movimiento Taxis");
        mnuEntradaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEntradaSalidaActionPerformed(evt);
            }
        });
        jMenu2.add(mnuEntradaSalida);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuTaxisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTaxisActionPerformed
        // TODO add your handling code here:
        mantTaxis frm =new mantTaxis(this,true);
        frm.setVisible(true);
    }//GEN-LAST:event_mnuTaxisActionPerformed

    private void mnuPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPersonasActionPerformed
        // TODO add your handling code here:
        mantPersonas frm =new mantPersonas(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_mnuPersonasActionPerformed

    private void mnuCooperativasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCooperativasActionPerformed
        // TODO add your handling code here:
        mantCooperativas frm =new mantCooperativas(this,true);
        frm.setVisible(true);
    }//GEN-LAST:event_mnuCooperativasActionPerformed

    private void mnuEntradaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEntradaSalidaActionPerformed
        // TODO add your handling code here:
        movTaxis frm =new movTaxis(this,true);
        frm.setVisible(true);
    }//GEN-LAST:event_mnuEntradaSalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem mnuCooperativas;
    private javax.swing.JMenuItem mnuEntradaSalida;
    private javax.swing.JMenuItem mnuPersonas;
    private javax.swing.JMenuItem mnuTaxis;
    // End of variables declaration//GEN-END:variables
}
